# 网站基础信息
title: Elena Rostova
email: e.rostova@nexus.edu
avatar: "https://api.dicebear.com/7.x/notionists/svg?seed=Elena"

# 简介 (支持双语)
desc_en: Postdoctoral Researcher @ Global Nexus Univ
desc_zh: 全球互联大学 · 博士后研究员

# 站点风格
site_style: academic

# 排除不需要编译的文件
exclude: [Gemfile, Gemfile.lock, README.md]
